
version: '3.8'

services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: mongodb://mongodb:27017
      DATABASE_NAME: blog_db
    ports:
      - '3002:3002'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'