version: '3.8'

services:
  nestjs-app:
    image: node:18-alpine
    container_name: simple_blog
    working_dir: /app
    volumes:
      - .:/app
    command: node dist/main
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: simple_blog_db
    ports:
      - "27017:27017"