version: '3.8'

services:
  nestjs-app:
    image: node:18-alpine
    container_name: simple_blog
    working_dir: /app
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      DATABSE_URI=simple_blog_db://mongo:27017
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: simple_blog_db
    ports:
      - "27017:27017"