name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: docker login -u hunooor01 -p ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build Docker image
      run: docker build -t simple_blog .

    - name: Tag Docker image
      run: docker tag simple_blog hunooor01/simple_blog:latest

    - name: Push Docker image to DockerHub
      run: docker push hunooor01/simple_blog    

    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker login -u hunooor01 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker pull hunooor01/simple_blog:latest
          docker stop simple_blog || true
          docker rm simple_blog || true
          docker run -d --name simple_blog  -p 3002:3002 hunooor01/simple_blog:latest