name: Deploy on Push (SSH)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Log in to Docker
          run: |
            docker login -u hunooor01 -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build the docker image
        run: docker build -t simple_blog .

      

      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker run -p 3002:3002 -d simple_blog